---
- name: install
  yum: name=yum-utils
  
- name: copy nginx repository tamplate
  copy: 
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    

- name: ensure nginx is at the latest version
  yum: name=nginx state=latest
  
- name: start nginx
  service:
      name: nginx
      state: started
      